<?php

/**
 * This is the model base class for the table "skript_has_sprache".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SkriptHasSprache".
 *
 * Columns in table "skript_has_sprache" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $skript_idskript
 * @property integer $sprache_idsprache
 * @property string $gen_skript
 *
 */
abstract class BaseSkriptHasSprache extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'skript_has_sprache';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SkriptHasSprache|SkriptHasSpraches', $n);
	}

	public static function representingColumn() {
		return array(
			'skript_idskript',
			'sprache_idsprache',
		);
	}

	public function rules() {
		return array(
			array('sprache_idsprache', 'required'),
			array('sprache_idsprache', 'numerical', 'integerOnly'=>true),
			array('gen_skript', 'safe'),
			array('gen_skript', 'default', 'setOnEmpty' => true, 'value' => null),
			array('skript_idskript, sprache_idsprache, gen_skript', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'skript_idskript' => null,
			'sprache_idsprache' => null,
			'gen_skript' => Yii::t('app', 'Gen Skript'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('skript_idskript', $this->skript_idskript);
		$criteria->compare('sprache_idsprache', $this->sprache_idsprache);
		$criteria->compare('gen_skript', $this->gen_skript, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}