<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * followed by relations of table "user" available as properties of the model.
 *
 * @property integer $iduser
 * @property string $username
 * @property string $password
 *
 * @property Skript[] $skripts
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password', 'length', 'max'=>45),
			array('username, password', 'default', 'setOnEmpty' => true, 'value' => null),
			array('iduser, username, password', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'skripts' => array(self::HAS_MANY, 'Skript', 'user_iduser'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iduser' => Yii::t('app', 'Iduser'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'skripts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iduser', $this->iduser);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}